### ISSUE TITLE
BLE Sensors info card text missing

### ISSUE THREAD

**Issue by manuelzomer** [arduino/Arduino-Science-Journal-iOS#24]
**Describe the bug**
When connecting a BLE Sense and looking at the information cards of the sensors, they all have the "What’s going on?" title displayed but no text underneath.

**To Reproduce**
1. Connect a BLE Sense
2. Select a Sensor
3. Click on the "i" button
4. See missing text/misplaced title

**Expected behavior**
The  "What’s going on?" section should either be filled with content or the title should not be displayed. 

**Screenshots**
![IMG_0955](https://user-images.githubusercontent.com/47141795/94898877-949d3880-0492-11eb-9207-d6ce4e09bbf9.PNG)

**Comment by sbhklr** [comment]
I suggest we don't display the info button if no info is available for a certain sensor.

**Comment by emiliopavia** [comment]
@sbhklr basic info (the first paragraph) is required by the protocol and is always shown. I'll hide the paragraph title if no additional info are provided by the sensor.

**Comment by sbhklr** [comment]
@emiliopavia Can't we determine already on the sensor card if there is additional info available, and if there isn't we wouldn't even show the info button?

**Comment by emiliopavia** [comment]
@sbhklr But a sensor description is always available (that "Ambient temperature in C or F" you see in the screenshot). If we hide the info button there's no way to see that.

**Comment by sbhklr** [comment]
@emiliopavia You got a point there. Okay, let's do it the way you suggested.
