### ISSUE TITLE
BLE temperature sensor is missing icon on sensor card

### ISSUE THREAD

**Issue by manuelzomer** [arduino/Arduino-Science-Journal-iOS#25]
**Describe the bug**
The temperature sensor of the BLE Sense doesn't display any icon in its sensor card, it is the only sensor to do so.

**To Reproduce**
1. Connect BLE Sense
2. Select the temperature sensor
3. See missing icon on the sensor card

**Expected behavior**
The temperature sensor should display an icon on the sensor card like all other sensors.

**Screenshots**
![IMG_0956](https://user-images.githubusercontent.com/47141795/94899752-2194c180-0494-11eb-93d9-3a2c1e3099ff.jpg)

**Comment by sbhklr** [comment]
Fixed in e1874472ed13fd37cf2f3907aae4db27eb3609a6
